apiVersion: v1
kind: Service
metadata:
  name: _service-name_
  namespace: userlabs
spec:
  selector:
    app: jupyterlab-_id_
  ports:
    - name: http
      protocol: TCP
      port: _port_
      targetPort: 8888
