apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: userlabs
  name: jupyterlab-_id_
  labels:
    app: jupyterlab-_id_
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyterlab-_id_
  template:
    metadata:
      labels:
        app: jupyterlab-_id_
        user-jupyterlab: "true"
    spec:
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        userlabs: "true"
      tolerations:
        - key: "jupyter-jsc/userlabs"
          value: "true"
          effect: "NoSchedule"
      containers:
        - name: jupyterlab-_id_
          image: jupyter/all-spark-notebook:spark-3.1.2
          imagePullPolicy: IfNotPresent
          # command: ["/bin/bash", "/usr/local/bin/before-notebook.d/pre_start.sh"]
          # command: ["/bin/sh", "-c", "--"]
          # args: ["while true; do sleep 30; done;"]
          securityContext:
            runAsUser: 0
          ports:
            - containerPort: _port_
          resources:
            limits:
              memory: "_resource_limit_memory_"
              cpu: "_resource_limit_cpu_"
              # ephemeral-storage: "_resource_limit_storage_"
            requests:
              memory: "_resource_requests_memory_"
              cpu: "_resource_requests_cpu_"
          env:
            - name: JUPYTER_ENABLE_LAB
              valueFrom:
                configMapKeyRef:
                  name: jupyterlab-_id_-cm
                  key: JUPYTER_ENABLE_LAB
            - name: NB_UID
              valueFrom:
                configMapKeyRef:
                  name: jupyterlab-_id_-cm
                  key: NB_UID
            - name: JUPYTERHUB_STATUS_URL
              valueFrom:
                configMapKeyRef:
                  name: jupyterlab-_id_-cm
                  key: JUPYTERHUB_STATUS_URL
            - name: JUPYTERHUB_CANCEL_URL
              valueFrom:
                configMapKeyRef:
                  name: jupyterlab-_id_-cm
                  key: JUPYTERHUB_CANCEL_URL
            - name: JUPYTERHUB_API_URL
              valueFrom:
                configMapKeyRef:
                  name: jupyterlab-_id_-cm
                  key: JUPYTERHUB_API_URL
            - name: JUPYTERHUB_ACTIVITY_URL
              valueFrom:
                configMapKeyRef:
                  name: jupyterlab-_id_-cm
                  key: JUPYTERHUB_ACTIVITY_URL
            - name: JUPYTERHUB_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: jupyterlab-_id_-cm
                  key: JUPYTERHUB_CLIENT_ID
            - name: JUPYTERHUB_USER
              valueFrom:
                configMapKeyRef:
                  name: jupyterlab-_id_-cm
                  key: JUPYTERHUB_USER
            - name: JUPYTERHUB_SERVICE_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: jupyterlab-_id_-cm
                  key: JUPYTERHUB_SERVICE_PREFIX
            - name: JUPYTERHUB_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: jupyterlab-_id_-cm
                  key: JUPYTERHUB_BASE_URL
            - name: SERVERNAMESHORT
              valueFrom:
                configMapKeyRef:
                  name: jupyterlab-_id_-cm
                  key: SERVERNAMESHORT
            - name: SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: jupyterlab-_id_-cm
                  key: SERVICE_NAME
            - name: REMOTE_NODE
              valueFrom:
                configMapKeyRef:
                  name: jupyterlab-_id_-cm
                  key: REMOTE_NODE
            - name: REMOTE_PORT
              valueFrom:
                configMapKeyRef:
                  name: jupyterlab-_id_-cm
                  key: REMOTE_PORT
            - name: STARTUUIDCODE
              valueFrom:
                configMapKeyRef:
                  name: jupyterlab-_id_-cm
                  key: STARTUUIDCODE
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: jupyterlab-_id_-cm
                  key: PORT
            - name: JUPYTERHUB_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: jupyterlab-_id_-secret
                  key: JUPYTERHUB_API_TOKEN
          volumeMounts:
            - name: nfs-userdata
              mountPath: "/home/jovyan"
            - name: nfs-bin
              mountPath: "/usr/local/bin/before-notebook.d"
            - name: nfs-motd
              mountPath: "/opt/apps/motd"
      securityContext:
        fsGroup: 100
      volumes:
        - name: nfs-userdata
          nfs:
            path: /mnt/userlabs-data/userdata/allsparknotebook/_userid_
            server: 10.0.40.227
        - name: nfs-bin
          nfs:
            path: /nfs/jupyter-jsc-live/common/userlabs-jobs/_id_/bin
            server: 10.0.40.227
        - name: nfs-motd
          nfs:
            path: /nfs/jupyter-jsc-live/common/userlabs-jobs/_id_/motd
            server: 10.0.40.227
