#!/bin/bash
mount | grep "/mnt/JUST_HOMEs_readonly" > /dev/null
EC=$?
if [[ $EC -eq 0 ]];then
    echo "/mnt/JUST_HOMEs_readonly is already mounted"
else
    CMD=$(python3 /opt/apps/bin/bin/.uftp_ro.py)
    $CMD /mnt/JUST_HOMEs_readonly 2>/dev/null
    EC=$?
    if [[ $EC -eq 0 ]]; then
        if [[ -L /home/jovyan/JUST_HOMEs_readonly && -d /home/jovyan/JUST_HOMEs_readonly ]]; then
            :
        else
            ln -s /mnt/JUST_HOMEs_readonly /home/jovyan/JUST_HOMEs_readonly
            EC=$?
            if [[ $EC -eq 0 ]]; then
                echo "JUST mounted to /home/jovyan/JUST_HOMEs_readonly"
            else
                echo "JUST mounted to /mnt/JUST_HOMEs_readonly"
            fi
        fi
    else
        echo "JUST mount failed."
    fi
fi
