apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: userlabs
  name: jupyterlab-_id_
  labels:
    app: jupyterlab-_id_
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyterlab-_id_
  template:
    metadata:
      labels:
        app: jupyterlab-_id_
        user-jupyterlab: "true"
    spec:
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        node.kubernetes.io/instance-type: "m16.large-disk"
      containers:
        - name: jupyterlab-_id_
          image: rancher-jsc.fz-juelich.de:5000/jupyterjsc/user-jupyterlabs:0.5.1
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                  [
                    "/bin/bash",
                    "-c",
                    "/opt/apps/bin/bin/umount-judac; /opt/apps/bin/bin/umount-B2DROP;",
                  ]
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          command: ["/bin/bash", "/opt/apps/bin/start.sh"]
          # command: ["/bin/sh", "-c", "--"]
          # args: ["while true; do sleep 30; done;"]
          ports:
            - containerPort: _port_
          resources:
            limits:
              # memory: "_resource_limit_memory_"
              # cpu: "_resource_limit_cpu_"
              ephemeral-storage: "_resource_limit_storage_"
          env:
            - name: JUPYTERHUB_CANCEL_URL
              valueFrom:
                configMapKeyRef:
                  name: userlab-_id_-cm
                  key: JUPYTERHUB_CANCEL_URL
            - name: JUPYTERHUB_API_URL
              valueFrom:
                configMapKeyRef:
                  name: userlab-_id_-cm
                  key: JUPYTERHUB_API_URL
            - name: JUPYTERHUB_ACTIVITY_URL
              valueFrom:
                configMapKeyRef:
                  name: userlab-_id_-cm
                  key: JUPYTERHUB_ACTIVITY_URL
            - name: JUPYTERHUB_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: userlab-_id_-cm
                  key: JUPYTERHUB_CLIENT_ID
            - name: JUPYTERHUB_USER
              valueFrom:
                configMapKeyRef:
                  name: userlab-_id_-cm
                  key: JUPYTERHUB_USER
            - name: JUPYTERHUB_SERVICE_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: userlab-_id_-cm
                  key: JUPYTERHUB_SERVICE_PREFIX
            - name: JUPYTERHUB_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: userlab-_id_-cm
                  key: JUPYTERHUB_BASE_URL
            - name: SERVERNAMESHORT
              valueFrom:
                configMapKeyRef:
                  name: userlab-_id_-cm
                  key: SERVERNAMESHORT
            - name: SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: userlab-_id_-cm
                  key: SERVICE_NAME
            - name: REMOTE_NODE
              valueFrom:
                configMapKeyRef:
                  name: userlab-_id_-cm
                  key: REMOTE_NODE
            - name: REMOTE_HUB_PORT
              valueFrom:
                configMapKeyRef:
                  name: userlab-_id_-cm
                  key: REMOTE_HUB_PORT
            - name: STARTUUIDCODE
              valueFrom:
                configMapKeyRef:
                  name: userlab-_id_-cm
                  key: STARTUUIDCODE
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: userlab-_id_-cm
                  key: PORT
            - name: JUPYTERHUB_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: userlab-_id_-secret
                  key: JUPYTERHUB_API_TOKEN
          volumeMounts:
            - name: nfs-software
              mountPath: "/p/software/hdfcloud"
              readOnly: true
            - name: nfs-userdata
              mountPath: "/home/jovyan"
              subPath: "_userid_"
            - name: nfs-common
              mountPath: "/opt/apps/bin"
              subPath: "userlabs-mgr-jobs/_id_/bin"
      securityContext:
        fsGroup: 100
      volumes:
        - name: nfs-software-local
          hostPath:
            path: /p/software/hdfcloud
            type: Directory
        - name: nfs-software
          nfs:
            path: /
            server: 10.100.0.104
        - name: nfs-userdata
          nfs:
            path: /
            server: 10.100.0.105
        - name: nfs-common
          nfs:
            path: /
            server: 10.100.0.106
